#pragma once

// FROM GLFW3
#define PAPER_MOUSE_BUTTON_1         0
#define PAPER_MOUSE_BUTTON_2         1
#define PAPER_MOUSE_BUTTON_3         2
#define PAPER_MOUSE_BUTTON_4         3
#define PAPER_MOUSE_BUTTON_5         4
#define PAPER_MOUSE_BUTTON_6         5
#define PAPER_MOUSE_BUTTON_7         6
#define PAPER_MOUSE_BUTTON_8         7
#define PAPER_MOUSE_BUTTON_LAST      PAPER_MOUSE_BUTTON_8
#define PAPER_MOUSE_BUTTON_LEFT      PAPER_MOUSE_BUTTON_1
#define PAPER_MOUSE_BUTTON_RIGHT     PAPER_MOUSE_BUTTON_2
#define PAPER_MOUSE_BUTTON_MIDDLE    PAPER_MOUSE_BUTTON_3